// Code generated by mockery v2.43.2. DO NOT EDIT.

package retry

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Mocktimer is an autogenerated mock type for the timer type
type Mocktimer struct {
	mock.Mock
}

type Mocktimer_Expecter struct {
	mock *mock.Mock
}

func (_m *Mocktimer) EXPECT() *Mocktimer_Expecter {
	return &Mocktimer_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: d
func (_m *Mocktimer) Execute(d time.Duration) <-chan time.Time {
	ret := _m.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 <-chan time.Time
	if rf, ok := ret.Get(0).(func(time.Duration) <-chan time.Time); ok {
		r0 = rf(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan time.Time)
		}
	}

	return r0
}

// Mocktimer_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Mocktimer_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - d time.Duration
func (_e *Mocktimer_Expecter) Execute(d interface{}) *Mocktimer_Execute_Call {
	return &Mocktimer_Execute_Call{Call: _e.mock.On("Execute", d)}
}

func (_c *Mocktimer_Execute_Call) Run(run func(d time.Duration)) *Mocktimer_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *Mocktimer_Execute_Call) Return(_a0 <-chan time.Time) *Mocktimer_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mocktimer_Execute_Call) RunAndReturn(run func(time.Duration) <-chan time.Time) *Mocktimer_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocktimer creates a new instance of Mocktimer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocktimer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mocktimer {
	mock := &Mocktimer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
